# This workflow will periodically trigger a python script to scrape and save data. 
name: Scrape and Update Data

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight (UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: python scrape.py
